AMS/AMS/urls.py
from django.contrib import admin
from django.urls import path, include
from AMS import views

urlpatterns = [
    #path('',views.login_redirect,name='login_redirect'),
    #path('',views.home_redirect,name='home_redirect'),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

AMS/accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('signin/', auth_views.LoginView.as_view(template_name= 'accounts/signin.html'), name='signin'),
    path('signout/', auth_views.LogoutView.as_view(template_name= 'accounts/signout.html'), name='signout'),
    path('signup/', views.signup, name='signup'),
    path('register/<email_id>/',views.register,name='register'),
    path('flat_owner/', views.flat_owner_home,name='flat_owner_home'),
    path('tenant/new', views.add_new_tenant,name='add_new_tenant'),
    path('<name>/profile', views.user_profile,name='user_profile'),
    path('tenants/', views.tenants,name='tenants'),
    path('charges/', views.charges,name='charges'),
    path('expenditure/', views.expenditure,name='expenditure'),
    path('president/', views.president_home,name='president_home'),
    path('secretary/', views.secretary_home,name='secretary_home'),
    path('treasurer/', views.treasurer_home,name='treasurer_home'),
    path('office_bearer/', views.office_bearer_home,name='office_bearer_home'),
    path('user/profile/', views.view_profile, name='view_profile'),
    path('user/profile/edit/', views.edit_profile, name='edit_profile'),
    path('user/change-password/', views.change_password, name='change_password'),
    path('reset-password/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    path('reset-password/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/users/reset/done/'), name='reset_password_confirm'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view()),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view()),
    path('generate/',views.generate_otp,name='generate'),
    path('validate/',views.validate_otp,name='validate'),
    path('otp_verified/',views.otp_update, name='otp_update')
]

AMS/accounts/models.py
from __future__ import unicode_literals
from django.db import models, transaction
from django.contrib.auth.models import(
    User, AbstractBaseUser, PermissionsMixin, BaseUserManager
)
from django.db.models.signals import post_save
from django.dispatch import receiver
from .utils import regex_phone
from django.utils import timezone
#from .db_models import *
# Create your models here.
def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)

# class UserProfile(models.Model):
#     user = models.OneToOneField(User, on_delete = models.CASCADE)
#     name = models.CharField(max_length=50, blank=True)
#     flat_number = models.TextField(max_length=10)
#     door_number = models.TextField(max_length=10, blank=True)
#     recent_photo = models.ImageField(upload_to=user_directory_path)
#     id_proof = models.FileField(upload_to=user_directory_path)
#     father_name = models.CharField(max_length=50)
#     mother_name = models.CharField(max_length=50)
#     occupation = models.TextField(max_length=50)
#     communication_address = models.TextField(max_length=300)
#     communication_address_proof = models.FileField(upload_to=user_directory_path)
#     permanent_address = models.TextField(max_length=300)
#     permanent_address_proof = models.FileField(upload_to=user_directory_path)
#     mobile_number = models.CharField(max_length=10)
#     flat_occupancy_status = models.BooleanField(default=False)
#     copy_of_sale_deed = models.FileField(upload_to=user_directory_path)

# class TenantProfile(models.Model):
#     userprofile = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
#     name = models.CharField(max_length=50, blank=True)
#     father_name = models.CharField(max_length=50, blank=True)
#     mother_name = models.CharField(max_length=50, blank=True)
#     occupation = models.TextField(max_length=50, blank=True)
#     id_proof = models.FileField(upload_to=user_directory_path, blank=True)
#     recent_photo = models.ImageField(upload_to=user_directory_path, blank=True)
#     permanent_address = models.TextField(max_length=300, blank=True)
#     permanent_address_proof = models.FileField(upload_to=user_directory_path, blank=True)
#     mobile_number = models.CharField(max_length=10, blank=True)
#     email_id = models.EmailField(max_length=50, blank=True)
#     vehicle_type = models.TextField(max_length=30, blank=True)
#     vehicle_registration_number = models.CharField(max_length=30, blank=True)

# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         UserProfile.objects.create(user=instance)
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.userprofile.save()

class OTP(models.Model):
    contact = models.CharField(max_length=10, validators=[regex_phone()])
    is_otp_verified = models.BooleanField(default=False)

# class PasscodeVerify(models.Model):
#     mobile = models.IntegerField(primary_key=True)
#     passcode = models.CharField(max_length = 7,default='0000')
#     is_verified = models.BooleanField(default=False)
#     created_on = models.DateTimeField(auto_now_add=True)
 
#     def __str__(self):
#         return (str(self.mobile) + ',' + self.passcode)

# class UserBaseManager(models.Manager):
#     def get_by_natural_key(self,mobile):
#         return self.get(mobile = mobile)


# class UserBase(models.Model):
#     mobile = models.IntegerField(primary_key=True)
#     created_on = models.DateTimeField(auto_now_add=True)
#     token = models.CharField(max_length = 50,default = 'xyz')
#     is_active = models.BooleanField(default = False)
#     is_vendor = models.BooleanField(default=False)
    
#     REQUIRED_FIELDS =['email','door_number']
#     USERNAME_FIELD = 'mobile'

#     def is_active_user(self):
#         return self.is_active

#     def is_vendor(self):
#         return self.is_vendor

#     def __str__(self):
#         return self.mobile

# class User_OTP(models.Model):
#     mobile_number=models.CharField(max_length=10)
#     OTP = models.CharField(max_length=6, blank=True, null=True, default=None)

class UserManager(BaseUserManager):

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email,and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        try:
            with transaction.atomic():
                user = self.model(email=email, **extra_fields)
                user.set_password(password)
                user.save(using=self._db)
                return user
        except:
            raise

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self._create_user(email, password=password, **extra_fields)


class UserProfile(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(max_length=40, unique=True)
    contact = models.CharField(max_length=10, validators=[regex_phone()])
    door_number = models.TextField(max_length=10)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    created_at  = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    username = models.CharField(max_length=20,default='abc')

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['contact','door_number']

    def save(self, *args, **kwargs):
        super(UserProfile, self).save(*args, **kwargs)
        return self



class UserDetail(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.PROTECT)
    flat_number = models.TextField(max_length=10)
    recent_photo = models.ImageField(upload_to=user_directory_path)
    id_proof = models.FileField(upload_to=user_directory_path)
    father_name = models.CharField(max_length=50)
    mother_name = models.CharField(max_length=50)
    occupation = models.TextField(max_length=50)
    communication_address = models.TextField(max_length=300)
    communication_address_proof = models.FileField(upload_to=user_directory_path)
    permanent_address = models.TextField(max_length=300)
    permanent_address_proof = models.FileField(upload_to=user_directory_path)
    mobile_number = models.CharField(max_length=10)
    flat_occupancy_status = models.BooleanField(default=False)
    copy_of_sale_deed = models.FileField(upload_to=user_directory_path)


class ResetPassword(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='reset_passwords')
    token = models.CharField(max_length=100, unique=True,error_messages={'unique': 'This token has already been taken.'})
    expires_at = models.DateTimeField()
    is_used = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    

AMS/accounts/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
#from .models import UserProfile

class SignupForm(forms.Form):
    door_number = forms.CharField(max_length=30)
    mobile_number = forms.CharField(max_length=30)
    email_id = forms.EmailField(max_length=30)

    def clean(self):
        cleaned_data = super(SignupForm,self).clean()
        print(cleaned_data)
        print('is the cleaned data')
        door_number = self.cleaned_data.get('door_number')
        mobile_number = self.cleaned_data.get('mobile_number')
        email_id = self.cleaned_data.get('email_id')
        if not door_number and not mobile_number and not email_id:
            raise forms.ValidationError('All Field are Required')
        return cleaned_data
class RegistrationForm(forms.Form):
    # email = forms.EmailField(required=True)
    username = forms.CharField(max_length=20)
    password1 = forms.CharField(max_length=30)
    password2 = forms.CharField(max_length=30)
    # class Meta:
    #     model = UserProfile
    #     fields = (
    #         'username',
    #         'password1',
    #         'password2'
    #     )

    def clean(self):
        cleaned_data = super(RegistrationForm,self).clean()
        print(cleaned_data)
        print('is the cleaned data')
        username = self.cleaned_data.get('username')
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if not password1 and not username and not password2:
            raise forms.ValidationError('All Field are Required')
        return cleaned_data

    # def save(self, commit=True):
    #     user = super(RegistrationForm, self).save(commit=False)
    #     email = self.cleaned_data['email']
    #     if commit:
    #         user.save()
    #     else:
    #         raise forms.ValidationError(("This username has already existed."))

    #     return user

# class EditProfileForm(UserChangeForm):

#     class Meta:
#         model = UserProfile
#         fields = (
#             'email',
#             'first_name',
#             'last_name',
#         )

class ContactForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)
    message = forms.CharField(
        max_length=2000,
        widget=forms.Textarea(),
        help_text='Write here your message!'
    )
    source = forms.CharField(       # A hidden input for internal use
        max_length=50,              # tell from which page the user sent the message
        widget=forms.HiddenInput()
    )

    def clean(self):
        cleaned_data = super(ContactForm, self).clean()
        name = cleaned_data.get('name')
        email = cleaned_data.get('email')
        message = cleaned_data.get('message')
        if not name and not email and not message:
            raise forms.ValidationError('You have to write something!')

# class regForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ('first_name','last_name','username','password')
#         widgets = {
#         'password':forms.PasswordInput(attrs={'type':'password'})
#         }

# class regform1(forms.ModelForm):
#     class Meta:
#         model = UserProfile
#         fields = ('mobile_number',)

AMS/accounts/templates/accounts/change_password.html
{% extends 'index.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

AMS/accounts/templates/accounts/edit_profile.html
{% extends 'index.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block hero-body %}
    <div class="box container">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p}}
            <button class="button is-primary" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

AMS/accounts/templates/accounts/home.html
{% extends 'index.html' %}

{% block head %}
    <title>Home</title>
{% endblock %}

{% block body %}
    <section class="section">
        <div class="container has-text-centered">
            <header class="is-centered">
                <h1 class="title is-spaced has-text-weight-bold is-3">ABOUT US</h1>
                <h2 class="subtitle">
                    APARTMENT is a Web-based apartment management solution that enables owners of residential properties to
                    take complete control of every aspect of their business, including the rent, vacancy and maintenance cycles.
                    Its streamlines management of the rent cycle with key features such as tenant and lease tracking, full general ledger
                    accounting, automated rent and late fee reminders and on-demand reports.

                    Additionally, rent collection can be automated; and property managers can receive online payments via Buildium’s tenant
                    portal.
                    
                    Tenants and rental owners can submit requests online via its’s tenant and owner portals. Property managers can turn
                    these requests into work items and assign them for maintenance.
                </h2>
            </header>
        </div>
    </section>
    <section id="contact" class="section is-medium" style="background-color: linen">
        <div class="container">
            <div class="columns">
                <div class="column is-one-third">
                    <div class="section">
                        <br>
                        <h1 class="title">Get in Touch</h1>
                        <br>
                        <h5>Address:</h5><span>123 Qwerty, INDIA</span>
                        
                        <h5>Email:</h5>amansonkr@gmail.com
                        
                        <h5>Phone:</h5>+919129932523
                    </div>
                </div>
                <div class="column">
                    <div class="title-wrapper has-text-centered">
                        <h2 class="title is-2 is-spaced">Contact Us</h2>
                        <h3 class="subtitle is-5 is-muted">We'd love to hear your opinion about it!</h3>
                        <div class="divider is-centered"></div>
                    </div>
            
                    <div class="content-wrapper">
                        <div class="columns">
                            <div class="column is-6 is-offset-3">
                                <form>
                                    <div class="columns is-multiline">
                                        <div class="column is-6">
                                            <input class="input is-medium" type="text" placeholder="Enter your Name">
                                        </div>
                                        <div class="column is-6">
                                            <input class="input is-medium" type="email" placeholder="Enter your Email">
                                        </div>
                                        <div class="column is-12">
                                            <textarea class="textarea" rows="10" placeholder="Write someting ..."></textarea>
                                        </div>  
                                    </div>
                                    <div class="has-text-centered">
                                        <button type="button" class="button is-primary">Send Message</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

AMS/accounts/templates/accounts/home_flat_owner.html
{% extends 'index.html' %}

{% block hero-body %}
    <div class="box section container has-text-centered">
        <header is-center>
            <p>Welcome Flat Owner</p>
            <h1 class="title is-spaced has-text-weight-bold is-3">{{user.username}}</h1>
        </header>
    </div>
    {% if next %}
        {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
        {% else %}
        <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}
{% endblock %}

AMS/accounts/templates/accounts/home_office_bearer.html
{% extends 'index.html' %}

{% block hero-body %}
    <div class="box section container has-text-centered">
        <header is-center>
            <p>Welcome Office Bearer</p>
            <h1 class="title is-spaced has-text-weight-bold is-3">{{user.username}}</h1>
        </header>
    </div>
    {% if next %}
        {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
        {% else %}
        <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}
{% endblock %}

AMS/accounts/templates/accounts/home_president.html
{% extends 'index.html' %}

{% block hero-body %}
    <div class="box section container has-text-centered">
        <header is-center>
            <p>Welcome President</p>
            <h1 class="title is-spaced has-text-weight-bold is-3">{{user.username}}</h1>
        </header>
    </div>
    {% if next %}
        {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
        {% else %}
        <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}
{% endblock %}

AMS/accounts/templates/accounts/home_secretary.html
{% extends 'index.html' %}

{% block hero-body %}
    <div class="box section container has-text-centered">
        <header is-center>
            <p>Welcome Secretary</p>
            <h1 class="title is-spaced has-text-weight-bold is-3">{{user.username}}</h1>
        </header>
    </div>
    {% if next %}
        {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
        {% else %}
        <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}
{% endblock %}

AMS/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login Form</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
      $(function(){
        arr=[]
        $('#send').click(function(e){
          e.preventDefault();
          var user = $('#un').val();
          $.ajax({
            url:'{% url "generate"%}',
            data:{'user':user},
            success:function(data){
              if(data.search('@')>0){
                arr = data.split('@');
                $('#otpt').html(arr[0]);
              }
              else{
                $('#otpt').html(data);
              }
            }
          });
        });
        $('#eotp').keyup(function(){
          var eotp = $(this).val();
          if(eotp==arr[1]){
            $('#c').html("<br/>Varification Complete").css({'color':'green'});
            $('#loginbtn').removeAttr('disabled');
          }
          else{
            $('#c').html("Varification Pending");
          }
        });
      });
    </script>
  </head>
  <body>
    <div class="container bg-light py-5">
      <div class="row py-5 my-5">
        <div class="col-md-4 mx-auto">
          <div class="card p-3">
            <div class="card-head">
              <h2 class='card-title text-center'>Login Here</h2>
            </div>
            <div class="card-body">
              <form method="post">
                {% csrf_token %}
                <div class="form-group">
                  <input type="text" name="un" placeholder='Enter Username' class='form-control' id='un' value=""/>
                  <a href="#" id='send' class='card-link float-right pt-1'>Send OTP?</a>
                  <br/><span class='text-success' id='otpt'></span>&nbsp;<span class='text-danger' id='c'></span>
                </div>
                <div class="form-group">
                  <input type="text" name="" placeholder='Enter OTP' class='form-control' id='eotp' value=""/>
                </div>
                <div class='form-group'>
                  <input type="submit" class='btn btn-primary btn-block' id='loginbtn' value="Log In" disabled>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

AMS/accounts/templates/accounts/profile.html
{% extends 'index.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block hero-body %}
<div class="box container">
    <h1>Profile</h1>
    <p>User: {{ user }}</p>
    <p>First Name: {{ user.first_name }}</p>
    <p>Last Name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <a class="button is-primary is-medium is-normal" href="{% url 'edit_profile' %}">Edit Profile</a>
</div>
{% endblock %}

AMS/accounts/templates/accounts/register.html
{% extends 'index.html' %}

{% block hero-body %}
    <div class="box container section has-text-centered" style="max-width:363px;background-color:lightgoldenrodyellow">
        <header class="is-centered">
            <h1 class="title is-spaced has-text-weight-bold is-3">Welcome</h1>
            <p>Setup Username and password here!</p>
            <br>
        </header>
        <div>
            {% if form.errors %}
            <p>Please try again.</p>
            {% endif %}
            <form id='registerForm' method="POST" >
                {% csrf_token %}
                <div class="field">
                    <div class="control has-icons-left has-icons-right">
                        <input id="id_username" class="input" type="username" name="username" placeholder="Username" required autofocus>
                        <span class="icon is-small is-left">
                        <i class="fas fa-user"></i>
                        </span>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <div class="control has-icons-left">
                        <input id="id_password1" class="input" type="password" name="password1" placeholder="Password" required>
                        <span class="icon is-small is-left">
                        <i class="fas fa-lock"></i>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <div class="control has-icons-left">
                        <input id="id_password2" class="input" type="password" name="password2" placeholder="Confirm Password" required>
                        <span class="icon is-small is-left">
                        <i class="fas fa-lock"></i>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <button class="button is-primary is-medium is-normal is-fullwidth" type="submit">REGISTER</button>
                    </div>
                </div>
                <input type="hidden" name="next" value="{{ next }}">
            </form>
        </div>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function(e) {
            const form = document.getElementById('registerForm');
            const f = FormValidation.formValidation(
                form,
                {
                    fields: {
                        username: {
                            validators: {
                                notEmpty: {
                                    message: 'Username is required'
                                }
                            }
                        },
                        password1: {
                            validators: {
                                notEmpty: {
                                    message: 'Password is required'
                                }
                            }
                        },
                        password2:{
                            validators: {
                                identical: {
                                    compare: function() {
                                        return form.querySelector('[name="password1"]').value;
                                    },
                                    message: 'The password and its confirm are not the same'
                                }
                            }
                        }
                    },
                    plugins: {
                        trigger: new FormValidation.plugins.Trigger(),
                        bulma: new FormValidation.plugins.Bulma(),
                        icon: new FormValidation.plugins.Icon({
                            valid: 'fas fa-check',
                            invalid: 'fa fa-times',
                            validating: 'fas fa-sync'
                        }),
                    },
                }
            );
            form.querySelector('[name="password1"]').addEventListener('input', function() {
                f.revalidateField('Password2');
            });
        });
        </script>
{% endblock %}

AMS/accounts/templates/accounts/registration.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>REGISTER FORM</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <style media="screen">
      #id_first_name, #id_last_name{
        width:48.1%;
        float:left;

      }label{
        display:none;
      }
      #id_first_name, #id_last_name, #id_username, #id_password,#id_contact{

        margin: 10px 4px 10px 4px;
      }
      #id_last_name0{
        margin-left:10px;
      }
      .form-group > small{
        color:white !important;
      }
    </style>
    <script>
      var p = '';
      $(function(){
        $('#sotp').click(function(){
          var number = $('#id_contact').val();
          if(number.length != 10){
            alert("You entered incorrect number");
          }
          else{
            $.ajax({
              url:'{% url "generate"%}',
              data:{'number':number},
              success:function(data){
                p=data;
                if(p!=0){
                  $('#msg').html('OTP Sent!!! ');
                  $('#votp').css({'display':'block'});
                  $('#vrotp').css({'display':'block'});
                  $('#sotp').css({'display':'none'});
                }else{
                  $('#msg').html( 'something went wrong');
                } 
              }
            });
          }
        });
        $('#vrotp').click(function(){
          var d = $('#votp').val();
          $.ajax({
            url:'{% url "validate"%}',
            data:{'number':d,'p':p},
            success:function(data){
              if(data===1){
                $('#msg').html('OTP verification Success!!! ');
              }else{
                $('#msg').html('OTP verification Failed!!! ');
              }
              
            }
          });
        });
      });
    </script>
  </head>
  <body>
    <div class="container-fluid bg-light">
      <div class="row py-5">
        <div class="col-md-6 p-5 mx-auto bg-danger text-white">
          <h2>Register Here</h2>
          <form class="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form1.as_p }}
            <input type="button" class='btn btn-success btn-block my-2'  name="" value="Send OTP" id='sotp'>
            <input type="text" class='form-control' style='display:none;' placeholder="Enter OTP" id='votp'>
            <input type="button" class='btn btn-warning btn-block my-2' style='display:none;'  name="" value="verify OTP" id='vrotp'>
            <small class='text-success' id='msg'></small>
            <input type="submit" id='sb' name="register" class='btn btn-success btn-block' value="Register">
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

AMS/accounts/templates/accounts/signout.html
{% extends 'index.html' %}

{% block hero-body %}
<section class="hero-body box is-block is-relative is-white is-large">
    <div class="container has-text-centered">
        <header class="is-centered">
            <h1 class="title is-spaced has-text-weight-bold is-3">Sign Out</h1>
            <p>You have Signed out!</p>
        </header>
    </div>
</section>
{% endblock %}

AMS/accounts/templates/accounts/user_home.html
{% extends 'index.html' %}

{% block hero-body %}
    <div class="box section container has-text-centered">
        <header is-center>
            <p>Welcome</p>
            <h1 class="title is-spaced has-text-weight-bold is-3">{{user.username}}</h1>
        </header>
    </div>
    {% if next %}
        {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
        {% else %}
        <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}
{% endblock %}